
std::vector<std::string> flm_help = {
    {"=== How to run a test ==="},
    {""},
    {"Step 1: Configure your primary monitor to run the game on."},
    {"        Set the monitor to use free sync or have it set to an appropriate refresh rate."},
    {"Step 2: Run flm.exe"},
    {"        when you press the right Alt key, you should see a yellow capture region box."},
    {"Step 3: Run the game"},
    {"        Adjust the game scene placement so that the FLM capture region is situated in an area"}, 
    {"        where the scene transitions from dark to bright when the mouse is moved horizontally."},
    {"        Note: The bounding box will only show if the game is running in window mode."},
    {"Step 4: Select start measurements key sequence (default is ALT+T)"},
    {"        Wait for the capture process to start, it may take a few seconds to start as FLM process data"},
    {"        you should see the mouse move left and right in rapid concession while the application records"},
    {"        latency measurements.Some games may require you to press down on the mouse keys to move the mouse"},
    {"        left and right."},
    {"        Console output will show the running latency and frame latency when FLM detects a change"},
    {""},
    {"        RUN: .|.. FPS xx.xx, Latency xxx.x ms, x.xx frames"},
    {""},
    {"        A running series of dots and a vertical bar will indicate at what rate these"},
    {"        latency measurements are occurring."},
    {"Step 5: Select stop measurements and review the console outputs values."},
    {""},
    {"        Starting measuring"},
    {"        RUN: .... FPS xx.xx, Latency xxx.x ms, x.xx frames"},
    {"        Stopped measuring "},
    {""},
    {"=== How to change the capture codec for a test ==="},
    {""},
    {"   Running flm.exe with no command line option, will auto detect the systems vendor and GPU,"},
    {"   then it will select the best capture codec to use."},
    {"   if you want to override this feature, simply specify the capture codec to use in the command line."},
    {""},
    {"   Capture codec options:"},
    {""},
    {"   -AMF  : Capture frames using AMF codec  (Default option, works only for AMD GPU's)"},
    {"   -DXGI : Capture frames using DXGI codec (Works on any GPU connected to main display)"},
    {""},
    {"   Runtime options:"},
    {""},
    {"   -FG   : Use this flag when measurements are for games with frame generation enabled."},
    {""},
    {"   Example usage:"},
    {""},
    {"   flm.exe -DXGI"},
    {""},
    {"   Will use the desktop capture codec, which will run on any GPU supported by DX11"},
    {""},
    {"   For more details on this amd more see the users guide."},
};
